name = "cloudflare-mail2im"
main = "src/index.js"
compatibility_date = "2025-01-09"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false
preview_urls = false

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "22d241201fc143e09662141b209ceea8"
