name = "cloudflare-mail2im"
main = "src/index.js"
compatibility_date = "2025-01-09"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false
preview_urls = false

[observability.logs]
enabled = false

[env.dev]
routes = [
	{ pattern = "attachments.mail.iel.plus", custom_domain = true }
]
kv_namespaces = [
	{ binding = "KV", id = "22d241201fc143e09662141b209ceea8" }
]
r2_buckets = [
	{ binding = "R2", bucket_name = "mail2im" }
]

[env.dev.vars]
STORAGE_URL_PREFIX = "https://attachments.mail.iel.plus"

[env.dev.observability]
enabled = true

#[env.prod]
#routes = [
#	{ pattern = "attachments.mail.example.com", custom_domain = true }
#]
#kv_namespaces = [
#	{ binding = "KV", id = "00000000000000000000000000000000" }
#]
#r2_buckets = [
#	{ binding = "R2", bucket_name = "mail2im" }
#]
#
#[env.prod.vars]
#STORAGE_URL_PREFIX = "https://attachments.mail.example.com"
#
#[env.prod.observability]
#enabled = true
