name: Deploy

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Choose an environment to deploy to: <dev|staging|prod>"
                required: true
                default: "prod"
                options:
                    - dev
                    - staging
                    - prod
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
            - uses: actions/checkout@v4
            - name: Deploy
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  wranglerVersion: "3.103.2"
                  command: deploy --env ${{ github.event.inputs.environment }}
